/**
* @file trapezoidal.h
* @author Bex Saw
* @brief Helper function for trapezoidal velocity profile
* @version 0.1
*/

#pragma once
#include <cmath>
#include <cstdint>
#include "enc_math.h"

/**
* @note This profile takes in the ticks/s and then outputs the desired ticks/s for the left and right motors.
*       The trapezoidal profile will have a max speed, min speed, and acceleration/deceleration rate that can be tuned.
*/
namespace MM
{
class Trapezoidal
{
public:
    /**
     * @brief Configure profile limits in ticks/s and ticks/s^2.
     * @param min_speed_ticks Minimum speed floor during profile transitions.
     * @param max_speed_ticks Cruise/peak speed target.
     * @param accel_ticks_per_sec2 Acceleration rate.
     * @param decel_ticks_per_sec2 Deceleration rate.
     * @param total_distance_ticks Optional target distance in ticks.
     *        If <= 0, profile behaves as an acceleration ramp to max speed.
     */
    bool configure(float min_speed_ticks, float max_speed_ticks,
                   float accel_ticks_per_sec2, float decel_ticks_per_sec2,
                   int32_t total_distance_ticks = 0);

    /**
     * @brief Reset dynamic state while preserving configured limits.
     */
    bool reset();

    /**
     * @brief Advance the profile using measured encoder delta ticks for this step.
     */
    bool trapezoidal(const EncoderInput& input, float dt_sec);

    /**
     * @brief Current speed command generated by the profile (ticks/s).
     */
    float get_speed_setpoint() const
    {
        return speed_setpoint;
    }

    /**
     * @brief Absolute progress accumulated from encoder deltas (ticks).
     */
    int32_t get_progress_ticks() const
    {
        return progress_ticks;
    }

    bool is_complete() const
    {
        return complete;
    }

private:
    // Profile limits in tick-domain units.
    float max_speed{0.0f};
    float min_speed{0.0f};
    float accel_rate{0.0f};
    float decel_rate{0.0f};

    // Dynamic state.
    float speed_setpoint{0.0f};
    int32_t progress_ticks{0};
    int32_t distance_goal_ticks{0};

    bool complete{false};
};
}  // namespace MM