/**
* @brief System Clock Driver Header for STM32F4 Series
* @file sys_clk.h
* @author Bex Saw
* @date 2/19/26
*/

#pragma once
#include "stm32f411xe.h"
#include "stm32f4xx_hal.h"
#include "sys_clk.h"

namespace MM::Stmf4
{
class HwClk
{
public:
    /*
    *    HSI: High-Speed Internal clock, an internal RC oscillator that provides a fixed frequency (e.g., 16 MHz) for the system clock. 
    *         It is typically used when a stable and low-cost clock source is sufficient.
    *    HSE: High-Speed External clock, an external crystal or resonator that provides a more accurate and stable clock source for the system. 
    *        It is often used when precise timing is required, such as for USB communication or when using the PLL to achieve higher frequencies.
    */
    enum class configuration
    {
        HSI_16MHZ,  // Internal RC oscillator at 16 MHz (default after reset) PLL disabled
        SYSCLK_HSE_24MHZ,  // main “run” mode (PLL or HSE) at 24 MHz
        SYSCLK_HSE_64MHZ,  // Higher performance option (via PLL)
        HSE_8MHZ           // External crystal at 8 MHz (on STM32F4 boards)
    };

    /**
     * @brief Initializes the system clock based on the specified configuration
     * @param config The desired clock configuration
     * @return true if initialization was successful, false otherwise
     */
    bool init(configuration);

    /**
     * @brief Retrieves the current system clock frequency
     * @return The current system clock frequency in Hz
     */
    uint32_t get_freq() const
    {
        return hz;
    }

    /**
     * @brief Retrieves the current system clock source
     * @return The current system clock source as a configuration enum value
     */
    configuration get_source() const
    {
        return source;
    }

private:
    /* Will hold MAGIC numbers for I2c generated by cubeMX */
    uint32_t hz;
    configuration source;
};
}  // namespace MM::Stmf4